export const RESET_STATE = "CRUD_RESET_STATE";
export const CURRENT_ITEM = "CRUD_CURRENT_ITEM";

export const REQUEST_LOADING = "CRUD_REQUEST_LOADING";
export const REQUEST_SUCCESS = "CRUD_REQUEST_SUCCESS";
export const REQUEST_FAILED = "CRUD_REQUEST_FAILED";

export const CURRENT_ACTION = "CRUD_CURRENT_ACTION";
export const RESET_ACTION = "CRUD_RESET_ACTION";
export const SET_SERACH_STRING = "SET_SERACH_STRING";
export const SET_FILTER_STRING = "SET_FILTER_STRING";
export const SET_CREATE_MODAL_OPEN = "SET_CREATE_MODAL_OPEN";
export const SET_CREATE_MODAL_CLOSE = "SET_CREATE_MODAL_CLOSE";

export const TAGS_REQUEST_LOADING = "TAGS_REQUEST_LOADING";
export const TAGS_GET_SUCCESS = "TAGS_GET_SUCCESS";
export const TAGS_GET_FAILURE = "TAGS_GET_FAILURE";
export const TAG_CREATE = "TAG_CREATE";
export const TAG_CREATE_SUCCESS = "TAG_CREATE_SUCCESS";
export const TAG_CREATE_FAILURE = "TAG_CREATE_FAILURE";
